Reverting meeting.ts to v1 state
OfficeDev/microsoft-teams-library-js pull request #1110
Opened 2022-04-20 01:13 UTC by lakhveerk

1. Reverting meeting.ts to v1 state
2. Making necessary changes in test-app and unit tests'

2022-04-20 06:38 UTC, shrshindeMSFT submitted a review, later dismissed

2022-04-21 21:45 UTC, erinha commented on change/@microsoft-teams-js-32d4d6a0-f255-43dd-b341-877c0d63abf9.json
> +  "comment": "Updated meeting namespace to work as it did in v1 along with necessary changes to unit tests and teams-test-app",
Beautiful! 💯

2022-04-21 22:33 UTC, erinha commented on packages/teams-js/test/public/meeting.spec.ts
> +    it('should fail when called without a callback', () => {
nit: can you change this test case to say 'should fail when called  with a null callback'.

It's harder to distinguish between "without a callback" and "empty callback", IMO.

2022-04-21 23:46 UTC, erinha commented on packages/teams-js/test/public/meetingLegacy.spec.ts
As discussed offline, it looks like meeting.spec.ts is a superset of this file after the changes to meeting.ts. I think this file can be deleted.

2022-04-21 23:47 UTC, erinha commented on packages/teams-js/src/public/meeting.ts
>  export namespace meeting {
Similar to the [comments in the media.ts PR](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1101#discussion_r855583974), can you please add @deprecated tags to the namespace and APIs referencing version 2.0.0-beta.5?

2022-04-21 23:48 UTC, erinha requested changes
Few comments about the test files and @deprecated comments.

2022-04-22 13:59 UTC, shrshindeMSFT commented
LGTM!

2022-04-22 13:59 UTC, shrshindeMSFT approved these changes

2022-04-22 19:32 UTC, erinha approved these changes
Looks good!

2022-04-22 20:17 UTC, merged