Adding frameless unit test cases to app capability
OfficeDev/microsoft-teams-library-js pull request #1153
Opened 2022-05-04 19:10 UTC by shrshindeMSFT

- Adding missing frameless unit test cases to app capability.

2022-05-05 17:50 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
>      });
These are great additions! Unless I'm missing something, I think there are some more test cases that should be added to validate `app.initialize`:

- validating GlobalVars.hostClientType is set correctly
- validating the various capabilities `.initialize` functions are called (e.g., `authentication.initialize()`, `menus.initialize()`, etc.)
- validating GlobalVars.additionalValidOrigins is set correctly

2022-05-05 22:23 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +        expect(() => app.registerOnThemeChangeHandler(() => {})).toThrowError(
Can we define an emptyCallback and use it in the two places we're using this?

2022-05-05 22:23 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +        expect(() => app.registerOnThemeChangeHandler(() => {})).toThrowError(
And then we can add the `// eslint-disable-next-line @typescript-eslint/no-empty-function` above the emptyCallback declaration

2022-05-05 23:04 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
>      });
I think the same comments in the framed tests apply to the frameless ones for `app.initialize` test cases.

2022-05-05 23:05 UTC, erinha requested changes
Thanks for adding and organizing these tests! A couple comments.

2022-05-05 23:07 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +      it('app.notifyAppLoaded should not allow calls before initialization', () => {
Should we both with having this test twice? I don't think there is anything different in the setup between framed and frameless, unless I'm missing something?

2022-05-05 23:08 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +      it('app.notifyAppLoaded should not allow calls before initialization', () => {
Same with `app.notifySuccess` and `app.notifyFailure`

2022-05-05 23:09 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +      it('app.notifyAppLoaded should not allow calls before initialization', () => {
And `app.registerOnThemeChangeHandler`

2022-05-10 16:12 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +      it('app.notifyAppLoaded should not allow calls before initialization', () => {
Ah it turns out I'm wrong. There is a difference in setup between framed and frameless and that is the important part of these tests.

2022-05-10 16:13 UTC, erinha approved these changes

2022-05-10 17:48 UTC, TrevorJoelHarris commented on packages/teams-js/test/public/app.spec.ts
> +  describe('Framed - Testing app capbility', () => {
"capability"

2022-05-10 18:04 UTC, TrevorJoelHarris submitted a review, later dismissed

2022-05-10 22:34 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +  describe('Framed - Testing app capbility', () => {
Thanks!

2022-05-10 22:35 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +    describe('Testing app.initialize function', () => {
Love it

2022-05-10 22:37 UTC, erinha commented on packages/teams-js/test/public/app.spec.ts
> +        for (let i = 0; i < 100; i++) {
It came from v1 tests. Happy to make it 2.

2022-05-10 22:38 UTC, erinha approved these changes

2022-05-10 22:46 UTC, TrevorJoelHarris approved these changes

2022-05-10 23:29 UTC, merged