Release 1.12.1
OfficeDev/microsoft-teams-library-js pull request #1157
Opened 2022-05-05 16:20 UTC by ydogandjiev

This change updates the SDK version to 1.12.1 which will be the last release of the v1.x SDK. This minor version bump is needed to address an accidental regression introduced in v1.12.0 around the registerChangeSettingsHandler API.

2022-05-05 16:21 UTC, erinha approved these changes

2022-05-06 17:14 UTC, aeunms commented on README.md
> +<script src="https://statics.teams.cdn.office.net/sdk/v1.12.1/js/MicrosoftTeams.min.js" integrity="sha384-HmRb1xX74v8jZiukR88bXWmRgVO/3uU7eHP64Ng+fnU0kc9JPBauRiQCPkvEtSGF" crossorigin="anonymous"></s
Should we also edit lines 30 and 53 to contain 1.12.1 rather than 1.11.0?

2022-05-06 18:37 UTC, erinha requested changes
Agree with Angela's comment about updating all instances of 1.11.0

2022-10-20 18:40 UTC, TrevorJoelHarris commented
Messaged @ydogandjiev several weeks ago and didn't hear back. Going to close this due to inactivity.

2022-10-20 18:40 UTC, closed without merging