Fix broken images and paths
OfficeDev/microsoft-teams-library-js pull request #1218
Opened 2022-06-21 00:13 UTC by AE-MS

Some of the documentation I previously committed had broken images and links (due to it being sourced elsewhere).

* I have fixed up the images
* I have removed the links to source files since, while helpful, seem like something that is brittle and likely to break over time since people aren't going think of them as possibly being used as examples from this document. Anyone reading this document should know how to find the source file locations if needed.

2022-06-22 22:39 UTC, erinha commented
In architecture.md, I noticed from the previous PR a typo:

> Capabilities can be feature or content-based, such a `mail`, `calendar`, `chat`, `dialog`, `authentication`, etc.,...

Should be "such as `mail`..."

2022-06-22 22:42 UTC, erinha commented
Typo in architecture.md:

> It **strongly** discouraged that private capabilities be used for this purpose.

Missing "is" following "It".

2022-06-22 22:44 UTC, erinha commented
Note about recent change in architecture.md:

A language identifier was added to the code blocks in the "Adding an API that utilizes version checks for compatibility" section, but it was added as "json" where the code blocks are actually "TypeScript".

2022-06-22 22:50 UTC, erinha commented on packages/teams-js/devdocs/architecture.md
Next line in TypeScript not json.

2022-06-22 22:53 UTC, erinha requested changes
Thanks for making this change! Comments regarding a couple typos from the previous PR touching these files.

2022-06-29 19:53 UTC, erinha commented on packages/teams-js/devdocs/architecture.md
There are several code blocks in here that are mistyped as json and should be TypeScript (GitHub is not letting me highlight the line numbers 👎 ). Lines 57 and 76.

2022-06-29 19:54 UTC, erinha commented on packages/teams-js/devdocs/architecture.md
They could be javascript vs TypeScript, I'm not sure if it matters.

2022-06-29 19:55 UTC, erinha requested changes
Two more lines that are json but should be javascript/TypeScript.

2022-06-29 22:46 UTC, erinha approved these changes
🚀

2022-06-29 23:27 UTC, erinha commented
A change file is required, since the devdocs folder is under the packages/teams-js directory (which is what beachball looks at).

2022-06-29 23:43 UTC, erinha approved these changes
Beautiful change file comment!

2022-06-29 23:56 UTC, lakhveerk approved these changes
lgtm

2022-06-30 00:09 UTC, MarcinJuraszek approved these changes

2022-06-30 04:39 UTC, merged