Mark video APIs as beta
OfficeDev/microsoft-teams-library-js pull request #1219
Opened 2022-06-21 09:05 UTC by shilcare

Mark video APIs as beta. 
Resolves MicrosoftDocs/msteams-docs#6121

2022-06-21 16:52 UTC, ydogandjiev submitted a review, later dismissed

2022-06-21 16:55 UTC, manasisharma submitted a review, later dismissed

2022-06-21 22:29 UTC, MarcinJuraszek commented
This API shipped as part of v1, in _public_ folkder, without a @beta tag. So I'm not sure I understand how it's not really 'public'. It is. It shipped. Making it @beta or hiding it is a breaking change, as customers might have had taken a dependency on it. What am I missing here?

cc: @erinha

2022-06-22 01:47 UTC, shilcare commented
> This API shipped as part of v1, in _public_ folder, without a @beta tag. So I'm not sure I understand how it's not really 'public'. It is. It shipped. Making it @beta or hiding it is a breaking change, as customers might have had taken a dependency on it. What am I missing here?
> 
> cc: @erinha
Video APIs should not have been published as they are still in internal rings and are gated in Teams, so only a few known partners have access to these APIs for now.

2022-06-22 13:40 UTC, tdwhite0 commented
@MarcinJuraszek Yes this has been public in the code for a long time, it has never actually worked in Teams though or been officially documented. I've been watching this feature for a long time and have built some things with this: https://github.com/microsoft/teams-videoapp-sample. I've been hoping it would work eventually, so seeing it now marked hidden is a bummer.

2022-06-22 17:40 UTC, erinha commented
> > This API shipped as part of v1, in _public_ folder, without a @beta tag. So I'm not sure I understand how it's not really 'public'. It is. It shipped. Making it @beta or hiding it is a breaking change, as customers might have had taken a dependency on it. What am I missing here?
> > cc: @erinha
> 
> Video APIs should not have been published as they are still in internal rings and are gated in Teams, so only a few known partners have access to these APIs for now.

As per the comments on this PR #1213, unfortunately we've already shipped these APIs, so I think we're committed to supporting them, and hiding the documentation doesn't achieve this. I suggest you attend office hours to discuss your feature and its roadmap, given that it has already been publicly released and has not been previously reviewed. https://aka.ms/extendingteamsjssdk

2022-06-22 17:41 UTC, erinha commented
/azp run

2022-06-28 17:39 UTC, ydogandjiev submitted a review, later dismissed

2022-06-30 21:14 UTC, erinha requested changes
Comments about applying the beta tag to all functions/interfaces/enums/etc. within the `video` namespace.

2022-06-30 21:15 UTC, erinha commented
/azp run

2022-07-01 01:21 UTC, shilcare commented on change/@microsoft-teams-js-b58082cb-6568-4c24-89f6-c55c4ec296ff.json
> +  "comment": "mark video api as beta",
updated

2022-07-01 15:49 UTC, MarcinJuraszek commented
/azp run

2022-07-01 15:50 UTC, MarcinJuraszek commented
/azp run

2022-07-05 15:27 UTC, erinha approved these changes

2022-07-07 16:14 UTC, ydogandjiev approved these changes

2022-07-08 16:43 UTC, erinha commented
/azp run

2022-07-08 16:43 UTC, erinha approved these changes

2022-07-08 17:39 UTC, merged