Fix outdated references to `core` namespace in deeplink documentation
OfficeDev/microsoft-teams-library-js pull request #1248
Opened 2022-07-15 17:43 UTC by AE-MS

The documentation for `executedDeepLink` referenced an outdated/removed namespace (`core`) and was fixed.

I found one other outdated reference to `core` in the test app and also fixed it.

2022-07-15 17:53 UTC, erinha commented on apps/teams-test-app/src/components/PagesAPIs.tsx
> +    name: 'pages.shareDeepLink',
I'm curious if the e2e tests will fail with this change (unless you already updated them in the corresponding host sdk repo).

2022-07-15 17:54 UTC, erinha commented on change/@microsoft-teams-js-59318f7e-dc90-4d48-a1b2-5616fb3a6cef.json
> +  "comment": "Fixed outdated references to 'core.' namespace in documentation",
Preference is to enclose namespaces or other API types/interfaces/etc in backtick quotes.

2022-07-15 18:01 UTC, erinha requested changes
Thank you for making this change! Left a question about e2e test with this update and comment about formatting of change file.

2022-07-22 19:36 UTC, erinha approved these changes
🚀

2022-07-22 20:01 UTC, Ella-ly approved these changes

2022-07-22 20:06 UTC, TrevorJoelHarris approved these changes

2022-07-22 20:55 UTC, jadahiya-MSFT approved these changes

2022-07-22 21:30 UTC, merged