Add OutlookWin32 to HostName enum
OfficeDev/microsoft-teams-library-js pull request #1336
Opened 2022-09-07 21:48 UTC by MarcinJuraszek

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

Add a new value (`OutlookWin32`) to `HostName` enum.

### Main changes in the PR:

1. Add a new value (`OutlookWin32`) to `HostName` enum.

## Validation

### Validation performed:

N/A

### Unit Tests added:

No

### End-to-end tests added:

No

## Additional Requirements

### Change file added:

Yes

2022-09-14 05:14 UTC, lakhveerk submitted a review, later dismissed

2022-09-15 21:46 UTC, AE-MS commented on change/@microsoft-teams-js-8b731aef-816c-49f6-9435-5b79bc5b99ca.json
> +  "comment": "Added OutlookWin32 to HostName enum",
>HostName [](http://example.com/codeflow?start=36&length=8)

Can you please put this in backticks?

2022-09-15 21:46 UTC, AE-MS requested changes
:clock1:

2022-09-15 21:47 UTC, lakhveerk submitted a review, later dismissed

2022-09-15 22:07 UTC, jadahiya-MSFT approved these changes

2022-09-15 22:10 UTC, jadahiya-MSFT approved these changes

2022-09-15 22:31 UTC, AE-MS approved these changes
:shipit:

2022-09-15 22:38 UTC, erinha approved these changes

2022-09-15 23:54 UTC, merged