add internal and hidden tags to RH and Reaction APIs
OfficeDev/microsoft-teams-library-js pull request #1539
Opened 2023-01-18 17:14 UTC by JEugenio-GitHub

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description
Updating the RaiseHand and MeetingRection Meeting APIs with the @hidden and @internal tag in order to hide the documentation and let app developers know that it may not work in 3p apps yet.

### Main changes in the PR:

1. Add @hidden and @internal tags to the 

## Validation

### Validation performed:

1. None

### Unit Tests added:
No, just adding tags

### End-to-end tests added:
No

## Additional Requirements

### Change file added:

No, no file was generated when running the changefile command.

2023-01-18 17:28 UTC, TrevorJoelHarris requested changes

2023-01-18 17:28 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/meeting.ts
> +     * @hidden
I don't think you need to have the hidden tag on each member if the containing interface is marked as hidden, feel free to remove these inner ones

2023-01-18 17:38 UTC, TrevorJoelHarris approved these changes

2023-01-18 19:34 UTC, erikadoyle submitted a review, later dismissed
LGTM

2023-01-18 21:56 UTC, aeunms approved these changes

2023-01-18 21:57 UTC, TrevorJoelHarris commented
/azp run

2023-01-19 11:51 UTC, MarcinJuraszek commented
You'll need to create a change file using `yarn changefile`.

2023-01-19 19:29 UTC, TrevorJoelHarris commented
/azp run

2023-01-19 19:30 UTC, TrevorJoelHarris commented
/azp run

2023-01-19 19:31 UTC, TrevorJoelHarris approved these changes

2023-01-19 20:00 UTC, jekloudaMSFT approved these changes

2023-01-19 21:04 UTC, TrevorJoelHarris commented
/azp run

2023-01-19 21:48 UTC, merged