Remove legacy AFR endpoints
OfficeDev/microsoft-teams-library-js pull request #1625
Opened 2023-03-06 22:53 UTC by pradeepananth

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

This is a clean up PR for removing deprecated AFR endpoints from Live Share Host file.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. This is a clean up PR for removing deprecated AFR endpoints:
`ordererEndpoint`
`storageEndpoint`
from Live Share Host file.

## Validation

### Validation performed:

1. Removed deprecated endpoints in Live Share SDK  https://github.com/microsoft/live-share-sdk/blob/046a85e2fe778f1e84559f6c90992ecc17e6d5bc/packages/live-share/src/LiveShareClient.ts#L138 
2. YouTube app 

### Unit Tests added:

> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why they aren't necessary.

No, as they already exist and updated with the new endpoint.

### End-to-end tests added:

No

## Additional Requirements

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

Yes

2023-03-07 00:10 UTC, Stevenic approved these changes

2023-03-10 17:46 UTC, erinha commented
/azp run

2023-03-10 17:49 UTC, erinha commented
Looks like you're missing a changefile. Please see contributing.md for guidelines for how to create one. Since this interface is marked with the `@beta` tag, I think the change type is probably patch.

2023-03-10 17:49 UTC, erinha requested changes
Please add changefile

2023-03-10 17:57 UTC, erinha commented
/azp run

2023-03-10 17:59 UTC, erinha commented on change/@microsoft-teams-js-77061c12-8716-4a1d-8a14-c09b9d1041e4.json
> +  "comment": "Remove legacy AFR endpoints",
Change file guidelines require past tense, i.e., "Removed legacy endpoints from `IFluidTenantInfo` interface." (I don't know if any teams-js developers would know what "AFR" stands for, but if so, feel free to add that before "endpoints" in the message.)

2023-03-10 18:00 UTC, erinha commented on change/@microsoft-teams-js-77061c12-8716-4a1d-8a14-c09b9d1041e4.json
> +  "comment": "Remove legacy AFR endpoints",
Please note use of backticks as well

2023-03-10 18:00 UTC, erinha requested changes
Changefile formatting.

2023-03-10 19:28 UTC, erinha commented
/azp run

2023-03-10 19:28 UTC, erinha approved these changes

2023-03-11 02:47 UTC, Stevenic approved these changes

2023-03-13 17:25 UTC, AE-MS approved these changes
:shipit:

2023-03-13 17:37 UTC, merged