Address MS Learn docs build system warning and suggestion
OfficeDev/microsoft-teams-library-js pull request #1670
Opened 2023-03-25 00:04 UTC by erikadoyle

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

Minor fixes to address Microsoft Learn (API reference docs) build system warning and suggestion.

Fixes have been implemented (hard coded), validated, and published in the generated yml doc source and published live. This PR incorporates the fix into the source so it will continue to generate correctly in future doc updates.

### Main changes in the PR:

1. In **call.ts**, escape the open-angle bracket, as the markdown parser was dropping it as invalid html
2. In **tasks.ts**, update the link in the extended description from *TaskModuleDimension* to [DialogDimension](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialogdimension?view=msteams-client-js-latest). TaskModuleDimension is no longer exported in v2 and thus has no corresponding API reference page. Note that the link text still remains "TaskModuleDimension", as that seems faithful to the [underlying source](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/packages/teams-js/src/public/constants.ts#L100).

## Validation

Fixes have been implemented (hard coded), validated, and published in the generated yml doc source and published live. This PR incorporates the fix into the source so it will continue to generate correctly in future doc updates.

### Validation performed:

1. From [getDefaultSizeIfNotProvided(TaskInfo)](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/tasks?view=msteams-client-js-latest#@microsoft-teams-js-tasks-getdefaultsizeifnotprovided), click on the link with text: **TaskModuleDimension.Small**. Its no longer a broken link because it resolves to DialogDimension page.
2. From [StartCallParams `targets` property description](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/call.startcallparams?view=msteams-client-js-latest#@microsoft-teams-js-call-startcallparams-targets), notices that this string and enclosing angle brackets now render in the description: `<phonenumber>`

### Unit Tests added:

No

### End-to-end tests added:

N/A

## Additional Requirements

### Change file added:

No (didn't seem necessary?)

### Related PRs:

https://github.com/OfficeDev/msteams-client-docs-ref-typescript/pull/123/files

2023-03-27 20:19 UTC, TrevorJoelHarris submitted a review, later dismissed

2023-03-28 17:44 UTC, AE-MS requested changes
Waiting for changefile addition and answer to question.  😀

2023-03-28 17:44 UTC, AE-MS commented on packages/teams-js/src/public/tasks.ts
> +   * otherwise uses the height and width values corresponding to {@link DialogDimension | TaskModuleDimension.Small}
This is kind of funny and maybe it's just a docs issue. It seems like `TaskModuleDimension` is still defined and exported:
https://github.com/OfficeDev/microsoft-teams-library-js/blob/993debfdc0dfba68bdf3126bc936627c210cc5bd/packages/teams-js/src/public/constants.ts#L100
...but it's really just an alias (re-export) of the `DialogDimension` type. Do re-exports like this not show up in documentation?

2023-03-30 20:48 UTC, erikadoyle commented on packages/teams-js/src/public/call.ts
When I ran `pnpm beachball` it returned "No change files are needed". I pulled the latest from main so hopefully that resolves the build issues.

2023-03-30 21:50 UTC, AE-MS commented on packages/teams-js/src/public/call.ts
I am 99.9% sure that this requires a changefile. Usually when you get this message, it means that your fork's main branch isn't up-to-date with the upstream's main branch.

If you go to the [main branch for your fork page on github](https://github.com/erikadoyle/microsoft-teams-library-js/tree/main) and press this "update branch" button:
![image](https://user-images.githubusercontent.com/36546967/228972273-bd4ce265-3dbb-47b5-8f6b-e9f768c3581b.png)
...then try to run `pnpm run changefile` does it still tell you nothing is needed?

2023-03-30 21:51 UTC, AE-MS submitted a review, later dismissed

2023-03-30 22:40 UTC, AE-MS commented on packages/teams-js/src/public/call.ts
You may also have to pull main locally after doing that update but I'm not sure.

2023-03-31 00:15 UTC, erikadoyle commented on packages/teams-js/src/public/call.ts
Ah! I was running the command from repo root rather than teams-js. Just pushed my changefile.

2023-03-31 14:38 UTC, AE-MS approved these changes

2023-03-31 15:58 UTC, TrevorJoelHarris approved these changes

2023-03-31 15:58 UTC, merged