Unit Test Case Update: meeting.spec.ts
OfficeDev/microsoft-teams-library-js pull request #1739
Opened 2023-05-05 19:06 UTC by shrshindeMSFT

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

We now know that desktop has two existing implementations: 
``` 
 framed: Tabs are loaded inside iframe which is created inside electron webview.
```
``` 
frameless: Tabs are loaded directly inside webview. 
```
That means platform can be frameless or iframed based upon what implementation is being used. 
We know that web is always in iframe, and mobile is always frameless. We are going to use this information to name the mock windows correctly.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

Updated `meeting.spec.ts` to uniformly use `Utils` class instead of `FramelessPostMock`.

## Validation

### Validation performed:
N/A

### Unit Tests added:
Yes

### End-to-end tests added:
N/A

2023-05-05 23:16 UTC, jadahiya-MSFT approved these changes

2023-05-05 23:18 UTC, jekloudaMSFT requested changes

2023-05-05 23:49 UTC, jadahiya-MSFT commented on packages/teams-js/test/public/meeting.spec.ts
> +  describe('framed', () => {
Should this be Framed: registerLiveStreamChangedHandler?

2023-05-16 19:09 UTC, jekloudaMSFT approved these changes

2023-05-16 19:48 UTC, merged