Preventing payload modification when sending message to child window
OfficeDev/microsoft-teams-library-js pull request #1751
Opened 2023-05-16 18:55 UTC by SidGulatiMsft

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description
When Teams Hub sends a payload to the child application (Viva Connection), we are unnecessarily wrapping it in an array.
This code path doesn't get executed for other apps like Viva Engage, and that is leading to a divergence in what payload is received by the app's callback method.
Through this PR, I am preventing the payload from getting modified.

### Main changes in the PR:

1. Prevent the payload from getting wrapped in an array before sending to the child frame

### Unit Tests added:

> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why they aren't necessary.

No.
This is specific to secure-broker and unit tests for the same can't be added here.

### End-to-end tests added:

No

## Additional Requirements

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

Yes

### Next/remaining steps:

> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).

- [ ] Make a corresponding change in Teams hub, to wrap the payload in an array
- [ ] Ensure that the downstream app (Viva Connections) can handle the incoming payload correctly

2023-05-16 23:29 UTC, TrevorJoelHarris requested changes
Please make sure Graham also reviews this

2023-05-16 23:29 UTC, TrevorJoelHarris commented on package-lock.json
47,247 changes seems like too many changes. We don't currently have a package-lock.json file, why are you adding one?

2023-05-16 23:29 UTC, TrevorJoelHarris commented on change/@microsoft-teams-js-277568ef-041e-4cc5-8169-6c0f16f39cef.json
> +  "type": "patch",
```suggestion
  "type": "minor",
```

2023-05-16 23:29 UTC, TrevorJoelHarris commented on change/@microsoft-teams-js-277568ef-041e-4cc5-8169-6c0f16f39cef.json
> +  "comment": "Preventing the payload for child frame to get wrapped in an array.",
```suggestion
  "comment": "Embedded apps no longer incorrectly get their parameters wrapped in an array",
```

2023-05-17 17:41 UTC, AE-MS commented
There should be tests for this. @TrevorJoelHarris will/has opened a backlog item for our team to take care of that since it's a new class of tests and not something that would be reasonable for you to add as part of this PR.

2023-05-17 17:48 UTC, AE-MS approved these changes

2023-05-17 22:25 UTC, SidGulatiMsft commented on package-lock.json
removed

2023-05-17 22:26 UTC, SidGulatiMsft commented on change/@microsoft-teams-js-277568ef-041e-4cc5-8169-6c0f16f39cef.json
> +  "type": "patch",
done

2023-05-17 22:26 UTC, SidGulatiMsft commented on change/@microsoft-teams-js-277568ef-041e-4cc5-8169-6c0f16f39cef.json
> +  "comment": "Preventing the payload for child frame to get wrapped in an array.",
done

2023-05-17 22:33 UTC, GrahamMcMynn approved these changes

2023-05-17 22:47 UTC, SidGulatiMsft commented on change/@microsoft-teams-js-277568ef-041e-4cc5-8169-6c0f16f39cef.json
> +  "dependentChangeType": "minor"
@TrevorJoelHarris , I changed the "dependentChangeType" to minor. I am guessing that is ok?

2023-05-17 22:50 UTC, TrevorJoelHarris approved these changes

2023-05-17 22:52 UTC, AE-MS approved these changes

2023-05-18 00:16 UTC, merged