Update secondaryBrowser.ts
OfficeDev/microsoft-teams-library-js pull request #1866
Opened 2023-08-01 15:01 UTC by mobajemu-msft

2023-08-02 05:24 UTC, AE-MS approved these changes

2023-08-02 05:24 UTC, AE-MS commented
You'll have to create a changefile by running `pnpm changefile`

2023-08-07 18:32 UTC, erikadoyle commented on packages/teams-js/src/public/secondaryBrowser.ts
> +   * Open a URL in the secondary browser
Line breaks in source don't necessarily render in the published doc, so these three lines will probably publish as a run-on sentence. Could you add punctuation?

2023-08-07 18:36 UTC, erikadoyle requested changes
Minor change I just noticed, otherwise looks good

2023-08-22 16:01 UTC, TrevorJoelHarris commented on change/@microsoft-teams-js-4885f2ff-afee-4756-9192-4731c184d1ba.json
You probably shouldn't be deleting an existing changefile

2023-08-22 16:02 UTC, TrevorJoelHarris requested changes
It looks like you're deleting someone else's change, which is probably not what you intended to do

2023-08-22 16:47 UTC, mobajemu-msft commented on change/@microsoft-teams-js-4885f2ff-afee-4756-9192-4731c184d1ba.json
yea looks like something went wrong. thanks for the callout. will fix that

2023-08-22 17:25 UTC, mobajemu-msft commented
Third time is the charm #1889

2023-08-22 17:26 UTC, closed without merging