registerTextureStream before getTextureStream to avoid frame lost
OfficeDev/microsoft-teams-library-js pull request #1895
Opened 2023-08-25 06:28 UTC by WengHe

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

> Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. <Change 1>
2. <Change 2>

## Validation

### Validation performed:

1. <Step 1>
2. <Step 2>

### Unit Tests added:

> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why they aren't necessary.

<Yes/No>

### End-to-end tests added:

<Yes/No>

## Additional Requirements

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

<Yes/No>

### Related PRs:

> Remove this section if n/a

### Next/remaining steps:

> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).

> Remove this section if n/a

- [ ] Item 1
- [ ] Item 2

### Screenshots:

> Remove this section if n/a

| Before     | After      |
| ---------- | ---------- |
| < image1 > | < image2 > |

2023-08-28 10:06 UTC, lubobill1990 approved these changes

2023-08-28 10:06 UTC, lubobill1990 commented on packages/teams-js/src/internal/videoUtils.ts
> +  const generator = new MediaStreamTrackGenerator({ kind: 'video' });
return directly

2023-08-28 10:06 UTC, lubobill1990 commented on change/@microsoft-teams-js-b3109727-ff31-4dcb-bafc-b21748d8ce7b.json
> +  "comment": "Changed the other of registering texture stream",
The comment is too vague.

2023-08-28 16:02 UTC, TrevorJoelHarris commented
It seems like there should be some tests that verify that this change is working correctly

2023-08-28 16:02 UTC, TrevorJoelHarris requested changes

2023-08-28 20:22 UTC, AE-MS requested changes
Just waiting for other feedback to be addressed
:clock1:

2023-09-01 09:17 UTC, WengHe commented
> It seems like there should be some tests that verify that this change is working correctly

The change is internal, all the UTs are passed, and I did an end to end test by using the new package in a video app and verified it works well.

2023-09-01 09:21 UTC, WengHe commented on packages/teams-js/src/internal/videoUtils.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
updated, now we don't need it any more

2023-09-01 09:21 UTC, WengHe commented on change/@microsoft-teams-js-b3109727-ff31-4dcb-bafc-b21748d8ce7b.json
> +  "comment": "Changed the other of registering texture stream",
updated

2023-09-01 09:21 UTC, WengHe commented on packages/teams-js/src/internal/videoUtils.ts
> +  const generator = new MediaStreamTrackGenerator({ kind: 'video' });
updated

2023-09-01 15:40 UTC, TrevorJoelHarris approved these changes

2023-09-01 15:49 UTC, AE-MS approved these changes

2023-09-01 15:49 UTC, merged