Add tenantid to getauthtoken api
OfficeDev/microsoft-teams-library-js pull request #2100
Opened 2023-12-15 18:21 UTC by arsa-MSFT

Allow apps to pass tenantId in the getAuthToken call in order to support cross-tenant resources via Native Federated Tokens (NFTs). 

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

> Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. <Change 1>
2. <Change 2>

## Validation

### Validation performed:

1. <Step 1>
2. <Step 2>

### Unit Tests added:

> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why they aren't necessary.

<Yes/No>

### End-to-end tests added:

<Yes/No>

## Additional Requirements

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

<Yes/No>

### Related PRs:

> Remove this section if n/a

### Next/remaining steps:

> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).

> Remove this section if n/a

- [ ] Item 1
- [ ] Item 2

### Screenshots:

> Remove this section if n/a

| Before     | After      |
| ---------- | ---------- |
| < image1 > | < image2 > |

2024-01-17 22:06 UTC, TrevorJoelHarris approved these changes
Please make sure that @erinha also approves before merging

2024-01-22 18:57 UTC, erinha commented on change/@microsoft-teams-js-a8488fc1-1f5f-4495-817b-b1bc0c3d1af7.json
> +  "comment": "enable acquiring of access token for cross tenant resources",
```suggestion
  "comment": "Enabled acquiring of access token for cross-tenant resources",
```

2024-01-22 18:58 UTC, erinha requested changes
Please update changefile.

2024-01-22 19:51 UTC, erinha approved these changes

2024-01-22 19:52 UTC, TrevorJoelHarris approved these changes

2024-01-22 20:42 UTC, merged