Clean-up for 2.20.0 release
OfficeDev/microsoft-teams-library-js pull request #2167
Opened 2024-02-08 18:48 UTC by jadahiya-MSFT

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

> Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. <Change 1>
2. <Change 2>

## Validation

### Validation performed:

1. <Step 1>
2. <Step 2>

### Unit Tests added:

> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why they aren't necessary.

<Yes/No>

### End-to-end tests added:

<Yes/No>

## Additional Requirements

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

<Yes/No>

### Related PRs:

> Remove this section if n/a

### Next/remaining steps:

> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).

> Remove this section if n/a

- [ ] Item 1
- [ ] Item 2

### Screenshots:

> Remove this section if n/a

| Before     | After      |
| ---------- | ---------- |
| < image1 > | < image2 > |

2024-02-09 01:43 UTC, AE-MS commented on packages/teams-js/CHANGELOG.md
> +- Added apiVersionTag for telemetry in `Profile`, `Search`, `SecondaryBrowser`, `Settings`, `Sharing`, `StageView`, `VideoEffects` and `VisualMedia` capabilites
>`Profile`, `Search`, `SecondaryBrowser`, `Settings`, `Sharing`, `StageView`, `VideoEffects` and `VisualMedia` [](http://example.com/codeflow?start=39&length=109)

These capabilities should all be lower cased

2024-02-09 01:44 UTC, AE-MS commented on packages/teams-js/CHANGELOG.md
> +- Added apiVersionTags for telemetry in `Conversations`, `Files`, `Logs`, `MeetingRoom` and `Notifications` capabilities
>`Conversations`, `Files`, `Logs`, `MeetingRoom` and `Notifications` [](http://example.com/codeflow?start=40&length=67)

These should also be lower-cased

2024-02-09 01:44 UTC, AE-MS requested changes
:clock1:

2024-02-09 01:46 UTC, AE-MS approved these changes

2024-02-12 18:36 UTC, noahdarveau-MSFT approved these changes

2024-02-12 19:17 UTC, merged