Backed out const enum changes to public api
OfficeDev/microsoft-teams-library-js pull request #2257
Opened 2024-04-05 18:45 UTC by noahdarveau-MSFT

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

> Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. Initially when making the const enum changes , I made the changes with the understanding that string enums inherently did not get reverse mappings, so it would not be an issue to make all of the public string enums const. However, I have recently learned that by making an enum const, it not only removes the reverse mapping functionality, but completely removes the object at runtime, which could potentially lead to client issues if they are accessing any of the const enums at runtime such as through the `Object.values(<enum>)` method. This reintroduces some package size but is necessary as to not potentially cause issue with the next release. 

## Validation

### Validation performed:

1. <Step 1>
3. <Step 2>

### Unit Tests added:

> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why they aren't necessary.

<Yes/No>

### End-to-end tests added:

<Yes/No>

## Additional Requirements

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

<Yes/No>

### Related PRs:

> Remove this section if n/a

### Next/remaining steps:

> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).

> Remove this section if n/a

- [ ] Item 1
- [ ] Item 2

### Screenshots:

> Remove this section if n/a

| Before     | After      |
| ---------- | ---------- |
| < image1 > | < image2 > |

2024-04-05 20:53 UTC, erinha commented on change/@microsoft-teams-js-46bb0b2e-b9eb-4242-8a86-665f5cb915ba.json
> +  "comment": "Backed out some potential bug causing changes",
```suggestion
  "comment": "Backed out some potential bug-causing changes related to `const` enums.",
```

2024-04-05 20:53 UTC, erinha requested changes
change file comment to be more specific about the change

2024-04-05 21:03 UTC, maglims approved these changes

2024-04-05 23:34 UTC, jadahiya-MSFT approved these changes

2024-04-08 16:02 UTC, erinha approved these changes

2024-04-08 16:02 UTC, merged