[WIP][Task 9077652] Add an additional parameter for Handoff ID in composeMailWithHandoddId API
OfficeDev/microsoft-teams-library-js pull request #2663
Opened 2024-12-19 22:26 UTC by MengyiGong

…ail API

For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

> Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. <Change 1>
2. <Change 2>

## Validation

### Validation performed:

1. <Step 1>
2. <Step 2>

### Unit Tests added:

> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why they aren't necessary.

<Yes/No>

### End-to-end tests added:

<Yes/No>

## Additional Requirements

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

<Yes/No>

### Related PRs:

> Remove this section if n/a

### Next/remaining steps:

> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).

> Remove this section if n/a

- [ ] Item 1
- [ ] Item 2

### Screenshots:

> Remove this section if n/a

| Before     | After      |
| ---------- | ---------- |
| < image1 > | < image2 > |

2025-01-08 05:24 UTC, AE-MS commented on packages/teams-js/src/public/mail.ts
> +  handoffId?: string;
>string [](http://example.com/codeflow?start=14&length=6)

Is this ID really any possible string? Is "MengyiGong" a valid handoff Id?

2025-01-08 17:24 UTC, AE-MS commented on packages/teams-js/src/public/mail.ts
> + *
>* [](http://example.com/codeflow?start=1&length=1)

Can you add documentation for the `@returns` value?

2025-01-08 17:26 UTC, AE-MS commented on packages/teams-js/src/public/mail.ts
> +  handoffId?: string;
>? [](http://example.com/codeflow?start=11&length=1)

Is it really valid for this to be optional? When would someone use the `composeMailWithHandoff` function if they didn't have a handoff id to provide?

2025-01-08 17:34 UTC, AE-MS commented on change/@microsoft-teams-js-61f74ab4-102e-4a46-88bb-55dbf245fbc1.json
> +  "comment": "Removed Beta/Preview tag on `{namespace}` capability. To track availability of this capability across different hosts see https://aka.ms/capmatrix",
>Removed Beta/Preview tag on `{namespace}` capability. To track availability of this capability across different hosts see https://aka.ms/capmatrix", [](http://example.com/codeflow?start=14&length=148)

This doesn't seem right

2025-01-08 17:36 UTC, AE-MS requested changes
:clock1:

2025-01-08 19:33 UTC, AE-MS commented on packages/teams-js/src/public/mail.ts
> +  return callFunctionInHostAndHandleResponse<boolean, boolean>(
>callFunctionInHostAndHandleResponse [](http://example.com/codeflow?start=9&length=35)

Is it important that this function returns a `boolean` from the host SDK? Or can it just return void and receive an `SdkError` instead?

I believe it would allow you to use the simpler `callFunctionInHost` instead.

2025-01-08 20:02 UTC, MengyiGong commented on change/@microsoft-teams-js-61f74ab4-102e-4a46-88bb-55dbf245fbc1.json
> +  "comment": "Removed Beta/Preview tag on `{namespace}` capability. To track availability of this capability across different hosts see https://aka.ms/capmatrix",
Thanks for pointing it out! The changes were in local and not pushed yet. Updated!

2025-01-08 20:03 UTC, MengyiGong commented on packages/teams-js/src/public/mail.ts
> +  handoffId?: string;
Confirmed with @jenniferyellow , any string should be valid for `handoffId`.
Hopeful this link helps: https://eng.ms/docs/experiences-devices/opg/office-ai/app-copilot/onboarding/handoff/handoff

2025-01-08 20:09 UTC, MengyiGong commented on packages/teams-js/src/public/mail.ts
> +  handoffId?: string;
Thanks, and this is a good point. We are making a new sub-capability `composeMailWithHandoff` API , and the `handoffId` should be required. Updated to required.

2025-01-08 21:35 UTC, MengyiGong commented on packages/teams-js/src/public/mail.ts
> +  return callFunctionInHostAndHandleResponse<boolean, boolean>(
Thanks for your suggestion! That’s a great point about the `boolean` not being used anywhere in the host SDK. I’ve updated it to use `callFunctionInHost`.

2025-01-08 23:58 UTC, AE-MS commented
I'm signing off on this because the code looks okay but one of the questions I had on your host SDK PR about whether or not it is going to be a breaking API change might affect how this teamsjs PR is structured.

2025-01-08 23:58 UTC, AE-MS submitted a review, later dismissed

2025-01-09 01:02 UTC, MengyiGong commented
> I'm signing off on this because the code looks okay but one of the questions I had on your host SDK PR about whether or not it is going to be a breaking API change might affect how this teamsjs PR is structured.

Thanks @AE-MS  I will hold off this PR until I figure how we will structure the web APIs.

2025-01-11 00:07 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail.ts
> +export function composeMailWithHandoff(composeMailParamsWithHandoff: ComposeMailParamsWithHandoff): Promise<void> {
This looks like it would be a breaking change for any hosts that currently implement the mail capability, because we expect all functions that check the same isSupported to work (or not work) at the same time. If this is checked in as-is, then hosts that already implement the mail capability would keep responding to the existing functions but this new one would be ignored by them even though we told the app developer that it worked.

In order to make this change in a non-breaking way you would need to make a new file for your new capability (see the geolocation folder for an example) and then you'd have to have that function check a different (new) section of runtime in order to check if this new subcapability is supported on the current host.

I hope this makes sense, but if it would be helpful I'm happy to sit down and show you what I mean. Just let me know!

2025-01-11 00:08 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail.ts
> + * Compose a new email in the user's mailbox, opening it in the drafts UX instead of the standard email.
Any new function we add should be marked with the @beta tag so that developers know that the function may change or be broken with little or no warning. There should be other examples in the library you can check.

2025-01-13 23:28 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> + *
There should be a `@returns` section here which outlines that the function returns a promise and states when the promise resolves (for example, is it when the host has opened a compose mail window, or only after that window is closed?) Also should outline what errors the Promise can reject with.

2025-01-13 23:31 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> +   * Use this endpoint to retrieve the handoff payload when BizChat creates an email draft for external handoff.
Might be something to check with @jenniferyellow 

Where does a developer get a handoff id? This just being a string makes it tricky (at least, without any extra explanation) for a developer to understand what a "valid" handoffId is.

2025-01-13 23:31 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> +   * Use this endpoint to retrieve the handoff payload when BizChat creates an email draft for external handoff.
(If this can be more strongly typed than string that would also be great, but hard to say without knowing more about what the handoffId is)

2025-01-13 23:47 UTC, TrevorJoelHarris requested changes
This is looking good! Left some thoughts and comments, let me know if you have any questions.

2025-01-13 23:47 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> + * Used to interact with mail capability, including opening and composing mail.
The `@module` comment and every exported item in this file should include the following comment:

```typescript
 * @beta
```

2025-01-13 23:47 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> + * Used to interact with mail capability, including opening and composing mail.
This will print a blurb in the dev docs on this capability that looks like this: 

![image](https://github.com/user-attachments/assets/a6230084-ee1a-46af-9955-cf655f90373a)

You can work with PM to decide when the @beta tag gets removed

2025-01-13 23:47 UTC, TrevorJoelHarris commented on change/@microsoft-teams-js-61f74ab4-102e-4a46-88bb-55dbf245fbc1.json
> +  "comment": "Add an additional parameter for Handoff ID in `composeMailWithHandoffId` API ",
```suggestion
  "comment": "Added the`mail.handoff.composeMailWithHandoffId` function that allows passing a handoff id to the compose mail window.",
```

You may want to check with PM to find out what specific language to write here since this string will show up in the patch notes for developers.

2025-01-13 23:47 UTC, TrevorJoelHarris commented on apps/teams-test-app/src/components/MailAPIs.tsx
> +const CheckMailWithHandoffCapability = (): React.ReactElement =>
You will need to add new E2E tests for this function (see mail.json for the existing e2e tests).

You should also check with @alexneyman-MSFT - he recently introduced a new, simpler way to author e2e tests that could help you out a lot!

2025-01-13 23:47 UTC, TrevorJoelHarris commented on packages/teams-js/test/public/mail.spec.ts
> +    it('should not allow calls if runtime does not support mail', async () => {
Maybe should also have a test where mail is supported but mail.handoff is not

2025-01-13 23:47 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> +export function composeMailWithHandoff(composeMailParamsWithHandoff: ComposeMailParamsWithHandoff): Promise<void> {
Is there any validation of the input params that you could do here to make sure that only legal values are passed to the host? Any invalid props you can catch here are ones the host won't have to deal with in their layer!

2025-01-14 17:54 UTC, MengyiGong commented on packages/teams-js/src/public/mail.ts
> +export function composeMailWithHandoff(composeMailParamsWithHandoff: ComposeMailParamsWithHandoff): Promise<void> {
Sorry for the confusion, updated to sub-capability.

2025-01-14 17:55 UTC, MengyiGong commented on apps/teams-test-app/src/components/MailAPIs.tsx
> +const CheckMailWithHandoffCapability = (): React.ReactElement =>
Please correct me if I'm wrong, should we add e2e test after web PR changes get in otherwise e2e will fail?

2025-01-14 19:33 UTC, MengyiGong commented on packages/teams-js/test/public/mail.spec.ts
> +    it('should not allow calls if runtime does not support mail', async () => {
Thanks, updated the test with ` mail is supported but mail.handoff is not` case.

2025-01-15 00:14 UTC, MengyiGong commented on packages/teams-js/src/public/mail/handoff.ts
> +export function composeMailWithHandoff(composeMailParamsWithHandoff: ComposeMailParamsWithHandoff): Promise<void> {
Thanks for your suggestion! I’ve updated the changes to include email validation when the input contains email addresses.

2025-01-15 17:41 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> +function validateEmails(emails?: string[]): boolean {
We already have an email validation function that you can use: https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/packages/teams-js/src/internal/emailAddressValidation.ts

That function is less strict that what you have here; all it does is validate that the string isn't empty and that it contains an '@' character followed by a '.' character. The reason it's less strict is that email address validation for all possible valid email addresses using regex is very nearly impossible. Here's a stack overflow post that explains the complexity: https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression

Rather than try to support a regex that is hundreds of lines long we have this happy medium!

2025-01-15 17:43 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> + *
"promise resolves when the host SDK succeeds" is it possible to be more specific that this? My default assumption would be that the promise resolves after the compose window has opened successfully. Is that correct?

2025-01-15 20:51 UTC, MengyiGong commented on packages/teams-js/src/public/mail/handoff.ts
> +function validateEmails(emails?: string[]): boolean {
Thanks for the ref! Updated to using `validateEmailAddress`.

2025-01-15 20:53 UTC, MengyiGong commented on packages/teams-js/src/public/mail/handoff.ts
> + *
Thanks for the suggestion to make the comment more specific! Updated.

2025-01-15 22:14 UTC, MengyiGong commented on packages/teams-js/src/public/mail/handoff.ts
> +   * Use this endpoint to retrieve the handoff payload when BizChat creates an email draft for external handoff.
Hi @TrevorJoelHarris Based on the discussion with the PMs, requiring a non-empty string is reasonable, and we don't need to perform any validation on the handoffID for now. I updated with the `handoffId` empty string check and also updated the unit test with this test case. Thanks for bringing this up!

2025-01-16 21:18 UTC, AE-MS commented on packages/teams-js/src/public/mail/handoff.ts
> +      validateEmails(composeMailParams.bccRecipients);
What are the semantics of calling `composeMailWithHandoff` with `ComposeMailType.New` and passing empty arrays for `toRecipients`, `ccRecipients`, and `bccRecipients`? The current validation code would allow that case. Should that be an error?

2025-01-16 22:41 UTC, MengyiGong commented on packages/teams-js/src/public/mail/handoff.ts
> +      validateEmails(composeMailParams.bccRecipients);
This is the behavior of the composeMail API, and I will double-check with the PM. (Based on my understanding, using ComposeMailType.New without specifying toRecipients allows the user to save the email as a draft and edit the toRecipients, ccRecipients, and bccRecipients later.)

2025-01-16 23:45 UTC, MengyiGong commented on packages/teams-js/src/public/mail/handoff.ts
> +      validateEmails(composeMailParams.bccRecipients);
Confirmed with PM and this is a valid pattern.

2025-01-17 16:50 UTC, AE-MS submitted a review, later dismissed
:shipit:

2025-01-17 22:58 UTC, KangxuanYe commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +  "name": "Handoff ComposeMail",
ComposeMail is not part of subCapability Name right?

2025-01-17 23:02 UTC, KangxuanYe commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +          "expectedTestAppValue": "Error: Error: handoffId should not be null or empty string."
I think "Error: Error: ..." bug has been fixed? @TrevorJoelHarris , don't we?

2025-01-17 23:07 UTC, MengyiGong commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +  "name": "Handoff ComposeMail",
The sub capability named `mail.handoff`. `composeMail` is the API name under `mail.handoff` sub-capability. For example, `geoLocation.map.chooseLocation` is one of the APIs under `geoLocation.map` sub-capability, and `geoLocation.map` is the sub-capability of `geoLocation`.

2025-01-17 23:09 UTC, MengyiGong commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +  "name": "Handoff ComposeMail",
Updated to `Mail Handoff`

2025-01-17 23:10 UTC, KangxuanYe requested changes

2025-01-17 23:10 UTC, KangxuanYe commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +  "name": "Handoff ComposeMail",
Please follow naming convention like this file: https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/apps/teams-test-app/e2e-test-data/pages.fullTrust.json

(page.fullTrust as an example)

There is a strict check in iOS backward compatible side if you don't name it by this.

2025-01-17 23:26 UTC, AE-MS approved these changes
:shipit:

2025-01-17 23:32 UTC, TrevorJoelHarris commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +          "expectedTestAppValue": "Error: Error: handoffId should not be null or empty string."
As far as I know this still shows up in the Test App :(

2025-01-17 23:32 UTC, TrevorJoelHarris commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +          "expectedTestAppValue": "Error: Error: handoffId should not be null or empty string."
(And it's sort of hard to fix because of how many tests have been written assuming it's there)

2025-01-17 23:45 UTC, KangxuanYe approved these changes

2025-01-17 23:45 UTC, KangxuanYe commented on apps/teams-test-app/e2e-test-data/mail.handoff.json
> +          "expectedTestAppValue": "Error: Error: handoffId should not be null or empty string."
Okay, I will leave them to be existed still... I thought we have fixed them.

2025-01-17 23:59 UTC, TrevorJoelHarris commented on packages/teams-js/src/public/mail/handoff.ts
> +function validateEmails(emails?: string[]): boolean {
this is very minor but I don't think this function needs to return a boolean. If it had a return type of void that would probably be more correct - it would return nothing, but if any email addresses are invalid it throws an error. Alternatively, you could have it return a boolean and then catch errors in here and return false if one occurs. I'd do option 1, but it's up to you

2025-01-18 00:01 UTC, TrevorJoelHarris approved these changes

2025-01-18 04:11 UTC, merged