[Draft] Callback functionality for selectPeople and getContext
OfficeDev/microsoft-teams-library-js pull request #802
Opened 2021-12-27 23:06 UTC by jadahiya-MSFT

Added in TeamsJS v1 callback functionality for selectPeople and getContext.

2021-12-27 23:14 UTC, erinha commented
<p>Analyzed commit id : d832ab015469988220eab8cdf10537d948fb0520</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: fab455cb346aff158f9ca0de677cc8355d21b421</p>

2021-12-27 23:21 UTC, erinha commented
<p>Analyzed commit id : ee04b3a5ad1df3462de22eae5060351ca0579e7b</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: fab455cb346aff158f9ca0de677cc8355d21b421</p>

2021-12-28 00:24 UTC, erinha commented
<p>Analyzed commit id : d93c98391f294b2d06e77fa5fcfdf0dc7e6649bb</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: fab455cb346aff158f9ca0de677cc8355d21b421</p>

2021-12-30 21:30 UTC, erinha commented
<p>Analyzed commit id : 530e095fada16c611e4eb4b7e6515e6a6950b47b</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: bd112e44bd54dff4b1b231e9709ce6490a1b5076</p>

2022-01-04 17:53 UTC, erinha commented
<p>Analyzed commit id : 0565f39270fd3499315dea036107730692f62f97</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: 126f401aae255673ebb77e31804e0ee6bb2cb2f5</p>

2022-01-04 21:16 UTC, MarcinJuraszek submitted a review, later dismissed

2022-01-04 22:15 UTC, Ella-ly requested changes

2022-01-05 17:50 UTC, TrevorJoelHarris commented on apps/teams-test-app/src/components/PeopleAPIs.tsx
> +            setResult(JSON.stringify(people));
@Ella-ly I'm not sure I understand your code sample, but it looks like you have two identical else statements on the end. Do you just mean that the code should be updated to:

if (error) {
  setResult(JSON.stringify(error));
} else {
  setResult(JSON.stringify(people));
}

2022-01-05 18:01 UTC, Ella-ly commented on apps/teams-test-app/src/components/PeopleAPIs.tsx
> +            setResult(JSON.stringify(people));
Yes. Sorry if it is confusing. The code in the comment description is the full representation, the **suggested change** part is where the code change can be made.

2022-01-05 19:59 UTC, jadahiya-MSFT commented on apps/teams-test-app/src/components/PeopleAPIs.tsx
> +            setResult(JSON.stringify(people));
Whoops, my bad! Thanks Ella!

2022-01-05 20:08 UTC, erinha commented
<p>Analyzed commit id : c1591acf06f23ba867691d897f6a7017f5fdc1f1</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: 4e3f05ee3569953a280f1b7bba41332ef3db2200</p>

2022-01-06 23:34 UTC, TrevorJoelHarris submitted a review, later dismissed
:shipit:

2022-01-06 23:41 UTC, Ella-ly submitted a review, later dismissed

2022-01-07 17:44 UTC, MarcinJuraszek commented on apps/teams-test-app/src/components/PeopleAPIs.tsx
> +          return 'selectPeople()' + noHostSdkMsg;
Do we still need to return something here after your change to update how `withCallback` is defined (https://github.com/OfficeDev/microsoft-teams-library-js/commit/fa1cd710d0db4484bf970730e3908024a82f41fc)?

2022-01-20 00:14 UTC, Ella-ly commented on apps/teams-test-app/src/components/PeopleAPIs.tsx
> +import { noHostSdkMsg } from '../App';
No `noHostSdkMsg` is used in this file.

2022-01-20 00:14 UTC, Ella-ly commented on apps/teams-test-app/src/components/AppAPIs.tsx
> +          executeDeepLink(input);
I would suggest the code here to be:
```
       withCallback: (input, setResult) => {
          const onComplete = (status: boolean, reason?: string): void => {
            if (!status) {
              if (reason) {
                setResult(JSON.stringify(reason));
              } else {
                setResult("Status is false but there's not reason?! This shouldn't happen.");
              }
            } else {
              setResult('Completed');
            }
          };
          executeDeepLink(input, onComplete);
        },
```

2022-01-20 19:01 UTC, jadahiya-MSFT commented on apps/teams-test-app/src/components/PeopleAPIs.tsx
> +import { noHostSdkMsg } from '../App';
good catch

2022-01-20 23:36 UTC, Ella-ly submitted a review, later dismissed

2022-01-24 22:59 UTC, Ella-ly approved these changes

2022-01-26 18:39 UTC, merged