Change service connection for posting comment
OfficeDev/microsoft-teams-library-js pull request #816
Opened 2022-01-06 06:51 UTC by anmaur

- Change service connection name for posting comments with external account

2022-01-06 20:21 UTC, MarcinJuraszek commented on azure-pipelines.yml
> +    displayName: 'Post bundle analysis result as PR comment in gitHub'
should probably be `on GitHub`.

2022-01-10 14:43 UTC, MarcinJuraszek requested changes

2022-01-10 14:44 UTC, MarcinJuraszek commented on azure-pipelines.yml
> +    displayName: 'Post bundle analysis result as PR comment in gitHub'
eh, I hoped it would let me merge the suggested stuff in :(

2022-01-10 14:45 UTC, MarcinJuraszek approved these changes

2022-01-10 17:36 UTC, erinha approved these changes

2022-01-10 18:36 UTC, merged