Make the clean command work on non-Windows platform
OfficeDev/microsoft-teams-library-js pull request #824
Opened 2022-01-08 00:28 UTC by erinha

I think this is the only script command we have that isn't happy when you run it on a Mac. Tested it on Mac and Windows and it works on both.

2022-01-08 00:31 UTC, TrevorJoelHarris submitted a review, later dismissed
:shipit:

2022-01-08 00:42 UTC, erinha commented on package.json
> +    "clean:modules": "lerna clean -y && rm -rf node_modules",
Sadly I was too optimistic about it working on Windows. My test case was atypical and it looks like it won't work for all Windows developers. Going to use `rimraf` instead, as per a Stack Overflow article (thanks Aaron!). Stay tuned for the update.

2022-01-08 00:43 UTC, AE-MS commented
For posterity: per our discussion and testing, this doesn't work on Windows generally. There is no `rm` command on Windows. There is one in the git/bin directory, but that directory isn't in the PATH by default. We could perhaps doing something about that for engineers on our team but I suggested using rimraf instead

2022-01-08 00:43 UTC, AE-MS requested changes
:clock1:

2022-01-09 20:20 UTC, erinha commented on package.json
> +    "clean:modules": "lerna clean -y && rm -rf node_modules",
Fixed.

2022-01-10 17:15 UTC, AE-MS approved these changes
:shipit:

2022-01-10 17:33 UTC, merged